// RISC0 querier server: same /query API surface as the Nova querier.
// Query proofs are generated by default (set `RISC0_QUERY_PROOF=0` to disable).

include!("main_parts/common.rs");
include!("main_parts/queries.rs");
include!("main_parts/main_entry.rs");
